# import itertools

tome = [
    'FFILREWOTNSRHTNETYPSLHENOEONNAACHOTTONIRDRGTAEEPICO',
    'OOPUOATEEOANNEIROSNOAAMMUPISBSEIKTFATOAAETGELNNCEWS',
    'OHSSRTHUIDEOGOTUOIHEERTILRENTHDNHEUEEOAOUNTTFSTOFET',
    'TRITERNIDONBUDDYREPSIDYEAPHELRRHDINFOITEDITRIAETPEN',
    'RNMESFAUHFPOIHGPIEETLSOEBWTGSYNTENYNDTNNESAHLAAADEE',
    'MWOIUCCRHLCTDGFENWSTTCEPIEUUUTWOAHOMHFPCPAASODDEOHI',
    'UESIBOISDSIFILAEUDASWERRDSTSAEITESROPRTDNDEATPHUSRE',
    'OEBONSGNEFFEEEEAEOEETGATNEIEWEEERQIGIGEAENOSMCSSADD',
    ]

order = [i - 4 for i in [4, 8, 5, 9, 6, 10, 7, 11]]

translation = ""
shuffled_tome = [tome[i] for i in order]
for i in xrange(len(tome[0])):
    for line in shuffled_tome:
        translation += line[i]
print translation
